mysociety/popit-api

src/middleware/api-links.js
src/mongoose/json-transform.js

If the proxyBaseUrl option is set then we include a link as a proxy_url
key for each image to the base proxy url of images so CPI clients can
link to thumbnailed versions. It doesn't include any resizing parameters
which the clients will need to add themselves.
Fixes #mysociety/popit/707

include link to image proxy version with images

---

package.json
src/app.js

by default adds Access-Control-Allow-Origin: * to all GET requests
which means API calls work in ajax calls etc
Fixes mysociety/popit#691

add cors middleware and apply to API GET requests

---

src/app.js
src/exporter.js
test/exporter.js
test/rest.js

This allow the user to export all of their data in popolo format. There are 4 different endpoints for the export
- `/export.json` - All languages uncompressed - this will produce invalid popolo if the instance uses multiple language, but is portable between instances.
- `export.json.gz` - As above but gzipped
- `export-:language.json` - Just one `:language` uncompressed - this will produce valid popolo but can't be used on it's own to recreate a whole instance and its translations.
- `export-:language.json.gz` - As above but gzipped.
Part of #321

Popolo export

---

package.json
src/app.js

Because the UI is now using these modules it processes the request before it gets to the API, which seems to confuse the old bodyParser middleware and throws an error.
The simple solution is to switch the API to use the same modules as the UI.
Fixes https://github.com/mysociety/popit/issues/718

Switch the API to use body-parser and multer

---

src/mongoose/json-transform.js

Also cut down on duplicated code by moving the share URL generation code
into a 'private' method.
For mysociety/popit#707

remove // from image URLs

---

src/routes/info.js
test/apps.js
test/rest.js

As suggested in https://github.com/mysociety/popit/pull/703#issuecomment-69002984 this adds the export url to the API's metadata endpoint.

Add export_url to API metadata

---

src/mongoose/embed.js

Allow embedding posts referred to by memberships.
This seems so overly simple, I'm not sure why I didn't do it in the first place. It could well be that I'm missing something, but this appears to have the desired effect.
Fixes #111

Allow embedding the post for a membership

---

src/paginate.js
test/paginate.js

When paginating we don't want to keep all parameters because it can cause issue with jQuery's JSONP functionality (see 186c09bf738e4299bf4386864e3cd02e4cc6b7b5).
We do however want to keep user supplied parameters such as how many results per_page, what to embed and the q parameter for the current search.
This ensures that these parameters are kept and makes it easy to add other parameters to keep in the future.
Fixes #110

Preserve ?embed and ?q parameters when paginating

---

src/middleware/api-links.js
src/models.js
src/mongoose/embed.js
src/mongoose/json-transform.js
src/mongoose/membership-finder.js
src/routes/collection.get.js
src/routes/collection.post.js
src/routes/document.get.js
src/routes/document.put.js
src/routes/image.js
src/routes/merge.js
src/routes/search.js
src/transform.js

Previously we were using `eachSchema` and `schema.options.toJSON` to set various configuration options which affected how the json was rendered by mongoose's `toJSON` method. This was a flawed approach because data could leak between requests if two instances were setting different option simultaneously.
This pull request moves the url generation into a `transform.js` module, which fixes the race condition with url generation and also should make it reasonably trivial to fix https://github.com/mysociety/popit-api/issues/119.
Fixes https://github.com/mysociety/popit/issues/729

Fix url generation race condition

---

src/mongoose/json-transform.js
src/transform.js

Following on from https://github.com/mysociety/popit-api/pull/120 and https://github.com/mysociety/popit/issues/729 this moves the image_proxy bits into the new transform module.
Fixes https://github.com/mysociety/popit/issues/736

Fix image proxy url

---

src/filter.js
test/rest.js

The filter module was setting the id property of the returned document
first, then proceeding to iterate through the whole document and copy
properties across. This meant that when the document had an 'id' field
that didn't match the '_id' field (for whatever reason) it was
overwriting the 'id' property with an incorrect one.
This fix ensures that the returned document will always have the correct
id property matching the _id in the database. There is still the mystery
of how the ids came to differ in the first place, but at least this
masks that problem.
Fixes https://github.com/mysociety/popit/issues/730

Set id last so it doesn't get overwritten when filtering

---

package.json

This fixes the security issue with serve-static because this version of
express depends on a newer version of connect, which in turn depends on
a version of serve-static which isn't vulnerable to the open redirect
issue.
Fixes https://github.com/mysociety/popit/issues/742

Upgrade express to 3.19.2

---

src/routes/image.js

Rather than just `use()` the middleware and attach it to all routes make
it a named middleware then just use it in the places that need it.
I'm not entirely sure why it didn't work correctly previously, but this
fixes it.
Fixes https://github.com/mysociety/popit/issues/751

Explicitly use the saveImages middleware

---

src/app-setup.js

This makes it easier to trap auth errors on the client side by checking
the status code of the actual response, rather than the 401 being on the
preflight check.
Fixes https://github.com/mysociety/popit/issues/776

Run CORS preflight check before auth happens

---

src/mongoose/elasticsearch.js
src/routes/delete.js
src/versions/0.1.js
test/rest.js

This allows you to remove all the people, organizations, memberships and posts from an instance in one go. Alternatively you can just remove the records from an individual collection.
Fixes https://github.com/mysociety/popit/issues/464

Add bulk delete endpoints to the API

---

src/app-setup.js

Open Politicians needs to do things other than the import such as bulk
delete from an instance before performing the import. This change allows
it full access to the API.
Note that this change is *only* for Open Politicians, no other sites
will be able to access the site over CORS.

Allow openpoliticians full CORS permissions

---

src/routes/document.get.js
src/transform.js

This ensures that '?', '/' and other characters are properly encoded in the url so there are no accidental 404s.
Part of https://github.com/mysociety/popit/issues/769

Encode record id whenever it's included in a url

---

src/routes/image.js

The behaviour when you upload an image via the PopIt API at the moment
is that it is appended to the 'images' array.  It would be helpful to be
able to instead say that the image should be inserted at the front of
the 'images' array, so that it's the "primary" image for that person
(i.e. the one that is used for the 'image' property)
This commit introduces a special parameter called 'index' when POSTing a
new image, which can be either set to 'first', 'last', '0', '1', '2',
'3', etc. to insert the image at the start of 'images', the end of
'images' or at a specific index (where 0 is the first place in the
array).

Allow one to determine the position of an uploaded image in 'images'

---

src/mongoose/popolo.js
test/date-filter.js
test/rest-v0.1.js
test/util.js

Make sure the images ids in the API output are correct. When there is no schema defined the API doesn't know what to do with the _id field, so it serializes it to an object instead of a string.
Eventually I'd like all of the schemas in popit-api to be explicit like this (see https://github.com/mysociety/popit/issues/264#issuecomment-85448579 for more details on whats involved with that).
Fixes https://github.com/mysociety/popit/issues/470

Fix image ids in API output

---

src/routes/1.0/document.put.js
src/routes/document.put.js
test/rest-v0.1.js
test/rest-v1.0.0.js

When PUTing an update to a record the id field of each object in the images array should be cast to a mongo ObjectId if present.
Fixes https://github.com/mysociety/popit/issues/794

Cast incoming image ids to ObjectIds

---

src/transform.js

This is required because the images are now a model and setting unknown
attributes on a model requires the use of `.set`.
Fixes https://github.com/mysociety/popit/issues/811

Use .set to add url and proxy_url to the image

---

src/routes/1.0/collection.post.js
src/transform.js
test/rest-v0.1.js
test/rest-v1.0.0.js

This adds back the `proxy_image` property to the top level of each document by using `.get` to access the `proxy_url` on the images array. It also adds some tests to ensure there are no future regressions and in doing so fixes a problem with the 1.0.0-alpha version of the API, which wasn't passing responses through the transform module for post requests.

Fix proxy image property

---

package.json
src/routes/image.js

It seems unnecessary to trust the user of the API to get the MIME type
of an uploaded image correct, when we can infer the file type using
libmagic. (And this saves documenting the mime_type parameter...)
Since libmagic just looks for invariant magic numbers at fixed offsets
into binary files (to paraphrase the man page), it can't tell whether
a file is malformed (possibly maliciously), but this was a risk with
the existing code anyway, and if a browser or image library is subject
to buffer overruns or the like that's a much more serious problem than
just that PopIt might store and serve such a file.
In addition this makes sure that newly uploaded files will only be
served with an image/* Content-Type.  (Existing uploaded images will
still be served with whatever mime_type was specified …

Disallow non-image uploads & ignore the supplied mime_type

---

src/mongoose/embed.js
test/rest-v0.1.js
test/rest-v1.0.0.js

Allow specifying multiple things to embed in a membership by separating them with a comma.
/persons/bob?embed=membership.organization,membership.post
:memo: This diff is easier to read [without whitespace changes](https://github.com/mysociety/popit-api/pull/143/files?w=0)
Fixes https://github.com/mysociety/popit/issues/797

Allow comma separated embeds

---

src/exporter.js
src/routes/export.js
test/exporter.js

By running documents through the transform module before we create the
export we can add the url, html_url and various image related urls to
the json.
Fixes https://github.com/mysociety/popit/issues/827

Use transform to add urls before exporting
